amount = ""
merkle_indices = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
merkle_path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
merkle_root = ""
nullifier = ""
nullifier_hash = ""
recipient = ""
secret = ""
withdraw_amount = ""
